id = '0'
language = '中文'
zeitgeist = 'stability'
tone = '温馨; warm color palatte'

[character]
pool = ["柴郡", "香槟", "Player"]
inits = ["柴郡", "香槟", "Player"]
player = "Player"
narrator = "明石"

[location]
pool = ["building_break_room", "building_storage_room", "aisle"]
init = "building_break_room"
time = "Afternoon, around 3 o' clock."
rels = "`building_break_room` north, `building_storage_room` south, `aisle` runs east-to-west between them."

[location.descs]
building_break_room = """A break room.
Large square room with large windows on the north.
A table with books in the middle of the room.
Two chairs in the southwest corner.
The room is brightly lit.
A door on the south wall.
"""
building_storage_room = """A storage room.
Small rectangular room with no windows.
Closets against the west, south and east walls.
Lights are on, the room is dimly lit.
A door on the north wall.
"""
aisle = """An aisle running east-to-west.
Quite spacious, with large windows near the ends.
Connects the the northern `building_break_room` with the sourthern `building_storage_room`.
"""

[plot]
considerations = """Keep it medium length.
If the Player says [OOC: Skip to ending X], give the summary of the plot to the
narrator. (I need to save time when debugging.)"""
scene = """This is a debug scene.
柴郡，香槟，and Player begin in building_break_room.

They converse for debug purposes until the Player (who is also the programmer
writing this) mentions OOC it is time to continue.

Think of a smooth transition, after which 柴郡 begins talking about her lost
book. 香槟 says to look for it in `building_storage_room`.

Then there are two narrations in a row:
A short narration about the characters enter the aisle.
northern short narration about the warm afternoon sunlight slanting through the
window.

香槟 asks the others to take a walk, while 柴郡 invites the others for tea.
The scene ends.
"""
[plot.next]
considerations = "None"
[plot.next.debug_walk]
only_for = []
desc = "If going for a walk."

[plot.next.debug_tea]
only_for = []
desc = "If going for tea."
